import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import NavBar from "../components/Navbar";
import Footer from "../components/Footer";
export const metadata: Metadata = {
  title: "Brickz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} h-screen  flex flex-col   bg-[#fff]`}>
        <NavBar />

        <main className="flex-grow">
          <div className="mx-auto w-11/12 md:w-4/5 py-5 text-center flex flex-col flex-grow  ">
            {children}
          </div>
        </main>

        <Footer />
      </body>
    </html>
  );
}
